site_name: NoPy
site_description: An unofficial OOP interface for the Notion API.
repo_url: https://github.com/VisakhChekur/nopy
repo_name: VisakhChekur/nopy

nav:
  - Home:
      - Overview: index.md
      - Usage:
          - Databases: usage/database.md
          - Pages: usage/page.md
          - Properties: usage/properties.md
      - Supported Features: features.md
  - API Reference:
      - Client: api_reference/client.md
      - Enums: api_reference/enums.md
      - Notion Objects:
          - Database: api_reference/notion_objects/database.md
          - Page: api_reference/notion_objects/page.md
      - Object Properties:
          # - Base: api_reference/properties/base.md
          - Common Properties: api_reference/properties/common.md
          - Database Properties: api_reference/properties/db_props.md
          - Page Properties: api_reference/properties/page_props.md
      - Properties: api_reference/properties.md
      - Queries: api_reference/query.md
      - Exceptions: api_reference/errors.md

theme:
  name: "material"
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - navigation.top
    - navigation.tabs

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - toc:
      permalink: true

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [nopy/]
          options:
            show_root_full_path: false
            show_root_toc_entry: false
            members_order: source
            merge_init_into_class: true
          # import:
          #   - https://docs.python.org/3/objects.inv
